### PR TITLE
3.1

### PR DESCRIPTION
**Pull request by Freddo3000**
Resolved issues:

#24 

#22 

#19 

#16 (Added parameter)

#13

#12 

#10 

#2

### CODE REVIEW

**Comment by Andrees97** [comment]
Thanks for your work! Would you mind adding #25 to your edit? Its a simple extra instance to the combat brain.

Condition:
`_leader distance (_leader findNearestEnemy _leader) > 650`

Action:
`// return behaviour and speed to normal
_Beh = "SAFE";	_leader setBehaviour "CARELESS";
(group _leader) setSpeedMode "LIMITED";
(group _leader) setFormation "FILE";

// delete waypoints
while {(count (waypoints (group _leader))) > 0} do
{	deleteWaypoint ((waypoints (group _leader)) select 0);	};

// spawn regroup function
{	if (vehicle _x != _x) then { _x setPos position _leader	} else {}	} forEach units group _leader;

// debug msg
if (VCM_Debug) then {systemchat "COMBAT END";};`

Feel free to modify it.

**Comment by Freddo3000** [comment]
@Andrees97 That approach is simply way too heavy handed. Forcing "CARELESS" behaviour is a recipe for disaster, as that behaviour should only be used in very specific situations, and the regroup by telepor is simply bound to cause major problems.

**Comment by Andrees97** [comment]
The teleport was a temporary solution, ideally the units should regroup by foot, couldn't get it to work properly though.
As I said, you can simply change CARELESS for SAFE. The idea is to make AI return to 'normal' behaviour.

**Comment by aussie-battler** [comment]
@Freddo3000 Thanks for the fixes. Any chance of a download link to your Vcom 3.1 version please :)

**Comment by aussie-battler** [comment]
Cheers @Freddo3000 you are a legend.

**Comment by aussie-battler** [comment]
Hey @Freddo3000 I think you may have a typo in SQUADBEH.FSM:

Line 774: should start with precondition not condition
Line 792: should start with precondition not condition

I'm testing your updates now :) Thanks for looking into this.

**Comment by Freddo3000** [comment]
@aussie-battler 

If that's an issue then that's to do with the official FSM editor, since that is what I used.

**Pull request merged**
